### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ahkhanjani** [exonest/graphql-cache-control#4]
I hope this simple yet useful library keeps going.
If this is not possible, I'm willing to maintain it. @alitnk

**Comment by cerpinn** [comment]
Are there new changes that need to be made? If so, sure! Go ahead and make a PR.

**Comment by ahkhanjani** [comment]
It seems like you're not watching this repo, which makes me wonder why.
There are currently 3 open PRs. Please consider reviewing them. I would also like to add some new features.
Best Regards @alitnk

**Comment by cerpinn** [comment]
Wow. It's funny, for some reason I wasn't getting any notifications on the PRs. My apologies.
Will review them as soon as possible.

Thanks for tagging me, haha.

**Comment by cerpinn** [comment]
Also just noticed I've used `tsdx` in this project. 
I think Ideally, we should remove that and go for a more lightweight setup.

**Comment by ahkhanjani** [comment]
> Also just noticed I've used `tsdx` in this project. I think Ideally, we should remove that and go for a more lightweight setup.

Agreed
